language: python
sudo: required
python:
  - "2.7"
  - "3.5"
before_install: 
  - sudo mkdir -p /var/log/opensds/orchestration.log
  - sudo chmod 666 /var/log/opensds/orchestration.log

install:
  - pip install tox codecov

script:
  - tox

after_success:
  - codecov
